# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_squashed_0008_auto_20170324_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('message', 'Send SMS Message'), ('call', 'Make Voice Call')], default='call', max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='button',
            name='description',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='button',
            name='name',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='button',
            name='double_press_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='double_press_action', to='core.ButtonAction'),
        ),
        migrations.AlterField(
            model_name='button',
            name='long_press_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='long_press_action', to='core.ButtonAction'),
        ),
        migrations.AlterField(
            model_name='button',
            name='single_press_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_press_action', to='core.ButtonAction'),
        ),
    ]
