# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='double_press_action',
            field=models.CharField(choices=[('message', 'Send SMS Message'), ('call', 'Make Voice Call')], default='call', max_length=8),
        ),
        migrations.AddField(
            model_name='button',
            name='long_press_action',
            field=models.CharField(choices=[('message', 'Send SMS Message'), ('call', 'Make Voice Call')], default='call', max_length=8),
        ),
        migrations.AddField(
            model_name='button',
            name='single_press_action',
            field=models.CharField(choices=[('message', 'Send SMS Message'), ('call', 'Make Voice Call')], default='call', max_length=8),
        ),
        migrations.AlterField(
            model_name='button',
            name='button_id',
            field=models.CharField(max_length=16),
        ),
    ]
