# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170328_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='buttonaction',
            name='phone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Phone'),
            preserve_default=False,
        ),
    ]
