# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_model_update'),
        ('core', '0002_auto_20170323_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='organizations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization'),
        ),
    ]
