# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_button_organizations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='button',
            old_name='button_id',
            new_name='serial_number',
        ),
    ]
