# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 03:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170328_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='button',
            name='double_press_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='double_press_action', to='core.ButtonAction'),
        ),
        migrations.AlterField(
            model_name='button',
            name='long_press_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='long_press_action', to='core.ButtonAction'),
        ),
        migrations.AlterField(
            model_name='button',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='button',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='organizations.Organization'),
        ),
        migrations.AlterField(
            model_name='button',
            name='single_press_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_press_action', to='core.ButtonAction'),
        ),
        migrations.AlterField(
            model_name='buttonaction',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buttonaction',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='phone', to='core.Phone'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
