# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170323_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='double_press_action',
            field=models.CharField(choices=[('message', 'Send SMS Message'), ('call', 'Make Voice Call')], default='message', max_length=8),
        ),
    ]
