# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170329_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='button',
            name='double_press_action',
        ),
        migrations.AddField(
            model_name='button',
            name='double_press_action',
            field=models.ManyToManyField(blank=True, null=True, related_name='double_press_action', to='core.ButtonAction'),
        ),
        migrations.RemoveField(
            model_name='button',
            name='long_press_action',
        ),
        migrations.AddField(
            model_name='button',
            name='long_press_action',
            field=models.ManyToManyField(blank=True, null=True, related_name='long_press_action', to='core.ButtonAction'),
        ),
        migrations.RemoveField(
            model_name='button',
            name='single_press_action',
        ),
        migrations.AddField(
            model_name='button',
            name='single_press_action',
            field=models.ManyToManyField(blank=True, null=True, related_name='single_press_action', to='core.ButtonAction'),
        ),
    ]
