# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='serial_number',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
