# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170329_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='button',
            name='double_press_action',
        ),
        migrations.RemoveField(
            model_name='button',
            name='long_press_action',
        ),
        migrations.RemoveField(
            model_name='button',
            name='single_press_action',
        ),
        migrations.AddField(
            model_name='button',
            name='double_press_actions',
            field=models.ManyToManyField(related_name='double_press_actions', to='core.ButtonAction'),
        ),
        migrations.AddField(
            model_name='button',
            name='long_press_actions',
            field=models.ManyToManyField(related_name='long_press_actions', to='core.ButtonAction'),
        ),
        migrations.AddField(
            model_name='button',
            name='single_press_actions',
            field=models.ManyToManyField(related_name='single_press_actions', to='core.ButtonAction'),
        ),
    ]
