# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 03:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170329_0319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buttonaction',
            old_name='action',
            new_name='type',
        ),
    ]
