# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170329_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='buttonaction',
            name='message',
            field=models.TextField(default='type message here'),
            preserve_default=False,
        ),
    ]
