# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 20:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_apilog'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilog',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buttonaction',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='core.Phone'),
        ),
    ]
