# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 18:51
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Group

def add_coreuser_group(apps, schema_editor):
    if not Group.objects.filter(name="CoreUser").exists():
        Group.objects.create(name="CoreUser")

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170402_1531'),
    ]

    operations = [
        migrations.RunPython(add_coreuser_group),
    ]
