# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 04:29
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from core.models import ButtonAction, Phone

# [ba.id, phone.id, user.id]
transfer_matrix = []

def collect_ids(apps, schema_editor):
    for ba in ButtonAction.objects.all():
        try:
            user_id = ba.target_user.id
        except Exception as e:
            first_user = User.objects.first()
            user_id = first_user.id

        ba.target_user = user_id
        ba.save()


def backwards(apps, schema_editor):
    for ba in ButtonAction.objects.all():
        first_phone = Phone.objects.filter(user=ba.target_user).first()
        ba.target_user = first_phone
        ba.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170403_1851'),
    ]

    operations = [
        migrations.RunPython(collect_ids, backwards),
        migrations.AlterField(
            model_name='buttonaction',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='target_user', to=settings.AUTH_USER_MODEL),
        )
    ]
