# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 04:29
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import migrations, models
import django.db.models.deletion

from core.models import ButtonAction, Phone


def collect_ids(apps, schema_editor):
    for ba in ButtonAction.objects.raw("SELECT id, target_user_id FROM core_buttonaction"):
        try:
            phone = Phone.objects.get(id=ba.target_user_id)
            ba.recipient = phone.user
        except Exception as e:
            ba.recipient = User.objects.first()

        ba.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170609_0432'),
    ]

    operations = [
        migrations.RunPython(collect_ids, backwards)
    ]
