# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 18:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_create_necessary_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='button_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
