# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20170607_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buttonaction',
            name='target_user',
        ),
    ]
