# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 18:47
from __future__ import unicode_literals

from django.db import migrations

from core.models import Button
from organizations.models import Organization

def forwards(apps, schema_editor):
    for button in Button.objects.raw("SELECT id, organization_id FROM core_button"):
        organization = Organization.objects.get(id=button.organization_id)
        button.user = organization.owner.organization_user.user
        button.save()

def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_button_user'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse),
    ]
