# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20170609_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='button',
            name='organization',
        ),
    ]
