# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_buttonaction_target_user'),
        ('core', '0018_remove_button_organization'),
    ]

    operations = [
    ]
