# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 13:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_button_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='button_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
