# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_20170610_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='description',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
